### ISSUE TITLE
Cassander:2.2.4 was not working after restarting

### ISSUE THREAD

**Issue by itmoss** [Mashape/docker-cassandra#7]
I tried to run Cassandra with below commands on the Docker. sure, I am first  about cassandr 

``` sh
stop cassandra 
rm cassandra

docker run --restart=always --net="host" -v `pwd`/tmp:/tmp -v `pwd`/var/lib/cassandra:/var/lib/cassandra -v /etc/localtime:/etc/localtime:ro -it --name cassandra cassandra:2.2.4
```

At first time, I was work correctly ,however next time it didn't work correctly with some error messages. 
## error message as below ,

``` sh
ERROR 08:04:24 Fatal exception during initialization
org.apache.cassandra.exceptions.ConfigurationException: Found system keyspace files, but they couldn't be loaded!
    at org.apache.cassandra.db.SystemKeyspace.checkHealth(SystemKeyspace.java:728) ~[apache-cassandra-2.2.4.jar:2.2.4]
    at org.apache.cassandra.service.StartupChecks$9.execute(StartupChecks.java:297) ~[apache-cassandra-2.2.4.jar:2.2.4]
    at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:104) ~[apache-cassandra-2.2.4.jar:2.2.4]
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:162) [apache-cassandra-2.2.4.jar:2.2.4]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:529) [apache-cassandra-2.2.4.jar:2.2.4]
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:638) [apache-cassandra-2.2.4.jar:2.2.4]
```

Do you have greate solution about that ?

**Comment by itmoss** [comment]
Sorry, I think, it is another issue. 
thanks
